CREATE DATABASE IF NOT EXISTS {{{SQL_DATABASE_NAME}}};
USE {{{SQL_DATABASE_NAME}}};

CREATE USER IF NOT EXISTS {{{SQL_DATABASE_USERNAME}}} IDENTIFIED BY '{{{SQL_DATABASE_PASSWORD}}}';
GRANT ALL PRIVILEGES ON {{{SQL_DATABASE_NAME}}}.* TO '{{{SQL_DATABASE_USERNAME}}}';
FLUSH PRIVILEGES;
